name: crud_api
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies: 
  crypto: ^3.0.1
  dart_jsonwebtoken: ^2.3.2
  shelf: ^1.2.0
  shelf_modular: ^1.0.0
  shelf_multipart: ^0.1.0
  shelf_router: ^1.1.1
  shelf_router_generator: ^1.0.1
  supabase: ^0.2.8

dev_dependencies:
  build_runner: ^2.1.4
  lints: ^1.0.0
